repos:

  # Black
  repo: https://github.com/psf/black
  rev: main
  hooks:
    - id: black
      args: [
              --line-length=110,
              --extend-exclude=^migrations/,
                .
      ]
      pass_filenames: false

    
